[workspace]
members = [
    "./crates/rrg",
    "./crates/rrg-macro",
    "./crates/rrg-proto",
]

[workspace.package]
version = "0.1.0"
authors = ["Łukasz Hanuszczak <hanuszczak@google.com>"]
edition = "2018" # TODO(@panhania): Upgrade to `2021`.
