[workspace]
members = [
    "./crates/ospect",
    "./crates/rrg",
    "./crates/rrg-macro",
    "./crates/rrg-proto",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Łukasz Hanuszczak <hanuszczak@google.com>"]
edition = "2021"
