[package]
name = "rrg"
description = "Rust rewrite of GRR."
version = "0.1.0"
authors = ["Łukasz Hanuszczak <hanuszczak@google.com>"]
edition = "2018"

[workspace]
members = [".", "./macro", "./proto"]

[dependencies]
rrg-macro = { path = "macro/" }
rrg-proto = { path = "proto/" }

env_logger = { version = "0.9.0" }
fleetspeak = { version = "0.3.0" }
humantime = { version = "2.1.0" }
libc = { version = "0.2.126" }
log = { version = "0.4.17" }
protobuf = { version = "=2.8.2" }
structopt = { version = "0.3.26" }
byteorder = { version = "1.3.4" }
regex = { version = "1.5.5" }
lazy_static = { version = "1.4.0" }

chrono = { version = "0.4.11", optional = true }
flate2 = { version = "1.0.14", optional = true }
netstat2 = { version = "0.8.1", optional = true }
# TODO: Remove `rust-crypto` from project dependencies altogether. It is no
# longer maintained and can be replaced by smaller and more specialized crates.
rust-crypto = { version = "0.2.36", optional = true }
sha2 = { version = "0.8.1", optional = true }
sysinfo = { version = "0.14.1", optional = true }

[target.'cfg(target_family = "unix")'.dependencies]
# TODO: Implement custom extended attribute retrival, no need to employ third-
# party crates for this.
xattr = { version = "0.2.2" }

pnet = { version = "0.26.0", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
ioctls = { version = "0.6.1" }

proc-mounts = { version = "0.2.4", optional = true }
# TODO(https://github.com/google/rrg/issues/47): This should be a dev dependency
# but because of Cargo limitations [1] it has to be marked not as such. However,
# because it is hidden behind a feature flag, it should not be a big problem.
#
# [1]: https://github.com/rust-lang/cargo/issues/1596
fuse = { version = "0.3.1", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
winreg = { version = "0.7.0", optional = true }

[dev-dependencies]
rand = { version = "0.8.5" }
tempfile = { version = "3.3.0" }

[features]
default = [
    "action-insttime",
    "action-interfaces",
    "action-filesystems",
    "action-finder",
    "action-listdir",
    "action-memsize",
    "action-metadata",
    "action-network",
    "action-stat",
    "action-timeline",
]

action-insttime = ["dep:chrono", "dep:proc-mounts", "dep:winreg"]
action-interfaces = ["dep:pnet"]
action-filesystems = ["dep:proc-mounts"]
action-finder = ["dep:rust-crypto", "dep:sha2"]
action-listdir = []
action-memsize = ["dep:sysinfo"]
action-metadata = []
action-network = ["dep:netstat2", "dep:sysinfo"]
action-stat = []
action-timeline = ["dep:flate2", "dep:sha2"]

test-chattr = []
test-setfattr = []
test-fuse = ["dep:fuse"]

[[example]]
name = "timeline"
required-features = ["action-timeline"]
