[package]
name = "rrg"
description = "Rust rewrite of GRR."
version = "0.1.0"
authors = ["Łukasz Hanuszczak <hanuszczak@google.com>"]
edition = "2018"

[workspace]
members = [".", "./macro", "./proto"]

[dependencies]
fleetspeak = { version = "0.3.0" }
humantime = { version = "2.0.0" }
libc = { version = "0.2.81" }
log = { version = "0.4.8" }
protobuf = { version = "=2.8.2" }
rrg-macro = { path = "macro/" }
rrg-proto = { path = "proto/" }
simplelog = { version = "0.7.6" }
structopt = { version = "0.3.12" }
flate2 = { version = "1.0.14" }
byteorder = { version = "1.3.4" }
chrono = { version = "0.4.11" }
cfg-if = { version = "0.1.10" }
regex = { version = "1.3.9" }
lazy_static = { version = "1.4.0" }
rust-crypto = { version = "0.2.36" }

netstat2 = { version = "0.8.1", optional = true }
sha2 = { version = "0.8.1", optional = true }
sysinfo = { version = "0.14.1", optional = true }

[target.'cfg(target_family = "unix")'.dependencies]
pnet = { version = "0.26.0" }
xattr = { version = "0.2.2" }

[target.'cfg(target_os = "linux")'.dependencies]
proc-mounts = { version = "0.2.4" }
ioctls = { version = "0.5.1" }

[target.'cfg(target_os = "windows")'.dependencies]
winreg = { version = "0.7.0" }

[dev-dependencies]
rand = { version = "0.7.3" }
tempfile = { version = "3.1.0" }
diff = { version = "0.1.12" }

[target.'cfg(target_os = "linux")'.dev-dependencies]
fuse = { version = "0.3.1" }

[target.'cfg(target_family = "unix")'.dev-dependencies]
users = { version = "0.10.0" }

[features]
default = [
    "action-insttime",
    "action-interfaces",
    "action-filesystems",
    "action-finder",
    "action-listdir",
    "action-memsize",
    "action-metadata",
    "action-network",
    "action-stat",
    "action-timeline",
]

action-insttime = []
action-interfaces = []
action-filesystems = []
action-finder = ["dep:sha2"]
action-listdir = []
action-memsize = ["dep:sysinfo"]
action-metadata = []
action-network = ["dep:netstat2", "dep:sysinfo"]
action-stat = []
action-timeline = ["dep:sha2"]

test-chattr = []
test-setfattr = []
