[package]
name = "rrg"
description = "Rust rewrite of GRR."
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = [
    "action-insttime",
    "action-interfaces",
    "action-filesystems",
    "action-finder",
    "action-listdir",
    "action-metadata",
    "action-network",
    "action-stat",
    "action-timeline",
]

action-insttime = ["dep:chrono"]
action-interfaces = []
action-filesystems = []
action-finder = ["dep:digest", "dep:md-5", "dep:sha1", "dep:sha2"]
action-listdir = []
action-metadata = []
action-network = []
action-stat = []
action-timeline = ["dep:flate2", "dep:sha2"]

test-chattr = []
test-fuse = ["dep:fuse"]

[dependencies.ospect]
path = "../ospect"

[dependencies.rrg-macro]
path = "../rrg-macro"

[dependencies.rrg-proto]
path = "../rrg-proto"

[dependencies.argh]
version = "0.1.8"

[dependencies.fleetspeak]
version = "0.3.1"

[dependencies.humantime]
version = "2.1.0"

[dependencies.libc]
version = "0.2.126"

[dependencies.log]
version = "0.4.17"
features = [
    "std",
]

[dependencies.protobuf]
version = "2.27.1"

[dependencies.byteorder]
version = "1.3.4"

[dependencies.regex]
version = "1.5.5"

[dependencies.lazy_static]
version = "1.4.0"

[dependencies.chrono]
version = "0.4.11"
optional = true

[dependencies.digest]
version = "0.10.5"
optional = true

[dependencies.flate2]
version = "1.0.14"
optional = true

[dependencies.md-5]
version = "0.10.5"
optional = true

[dependencies.sha1]
version = "0.10.5"
optional = true

[dependencies.sha2]
version = "0.10.6"
optional = true

[target.'cfg(target_os = "linux")'.dependencies.ioctls]
version = "0.6.1"

# TODO(https://github.com/google/rrg/issues/47): This should be a dev dependency
# but because of Cargo limitations [1] it has to be marked not as such. However,
# because it is hidden behind a feature flag, it should not be a big problem.
#
# [1]: https://github.com/rust-lang/cargo/issues/1596
[target.'cfg(target_os = "linux")'.dependencies.fuse]
version = "0.3.1"
optional = true

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
]

[dev-dependencies.rand]
version = "0.8.5"

[dev-dependencies.tempfile]
version = "3.3.0"

[[example]]
name = "timeline"
required-features = ["action-timeline"]
