[package]
name = "rrg-proto"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies.ospect]
path = "../ospect"

[dependencies.rrg-macro]
path = "../rrg-macro/"

[dependencies.log]
version = "0.4.8"

[dependencies.protobuf]
version = "~3.2.0"

[dev-dependencies.quickcheck]
version = "1.0.3"

[dev-dependencies.quickcheck_macros]
version = "1.0.0"

[build-dependencies.protobuf-codegen]
version = "~3.2.0"

[build-dependencies.tempfile]
version = "3.1.0"
