[package]
name = "rrg-proto"
version = "0.1.0"
authors = ["Łukasz Hanuszczak <hanuszczak@google.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4.8" }
protobuf = { version = "2.27.1" }
rrg-macro = { path = "../rrg-macro/" }

[dev-dependencies]
quickcheck = { version = "1.0.3" }
quickcheck_macros = { version = "1.0.0" }

[build-dependencies]
protobuf-codegen-pure = { version = "2.27.1" }
tempfile = { version = "3.1.0" }
